name: OIDC Debug
on: push

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: dump JWT
        run: |
          curl -sH "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://example.service" | base64 -w0
      - name: Dump Context
        run: |
          echo github: '${{ toJson(github) }}'
          echo github: '${{ toJson(job) }}'
          echo github: '${{ toJson(steps) }}'
          echo github: '${{ toJson(runner) }}'
          echo github: '${{ toJson(strategy) }}'
      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: '${{ vars.ACTIONS_ID_TOKEN_REQUEST_URL }}'
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: '${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}'
